### ISSUE TITLE
Thumbnail 在首页不显示

### ISSUE THREAD

**Issue by sunzhaoyuan** [viosey/hexo-theme-material#543]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

你好，我想请问一下为什么我设置了thumbnail之后，在首页，没有文章显示出了thumbnail，取而代之的全部都是纯蓝色的颜色。不过，在点进了相应的文章之后，thumbnail显示正常。非常感谢！
![image](https://user-images.githubusercontent.com/22965844/31254700-cf3f25f0-a9f7-11e7-861f-17abea4801ed.png)
这个是首页的样子

![image](https://user-images.githubusercontent.com/22965844/31254747-ee90a7a8-a9f7-11e7-9a8f-67bfa2cdf1c1.png)
这个是文章页的样子

**Comment by neoFelhz** [comment]
See #498 for details.

**Comment by utkuufuk** [comment]
@neoFelhz #498 is not related to the problem that @sunzhaoyuan mentioned. I'm having the same issue here. It's not about random thumbnails.

Say I have a post named `fìsh`. Then I have a file named `fìsh.md` located in `source/_posts/` and the directory `source/_posts/fish` where I put my my thumbnail image `fish.png`.

Then, when I add the line:
```
thumbnail: fish.png
```
to the front matter of `fish.md`, it only shows up when I go to the `fish` post, but I can't see the thumbnail from the homepage where the header of the `fish` post is shown. It shows a plain blue background instead as @sunzhaoyuan mentioned.

However thumbnails work properly when given as web URLs instead of relative links.

@viosey @neoFelhz can you tell us how to solve this issue please?
